create extension if not exists pgcrypto;

create table if not exists public.devices (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  model text,
  platform text,
  status text not null default 'OFFLINE' check (status in ('ONLINE','OFFLINE','POWERED_OFF','UNREACHABLE')),
  battery_pct integer check (battery_pct between 0 and 100),
  last_seen_at timestamptz,
  last_latitude double precision,
  last_longitude double precision,
  last_location_accuracy_m double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.location_events (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.devices(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  accuracy_m double precision,
  battery_pct integer check (battery_pct between 0 and 100),
  recorded_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null unique references auth.users(id) on delete cascade,
  plan text not null default 'BASIC' check (plan in ('BASIC','PLUS','FAMILY')),
  status text not null default 'INACTIVE' check (status in ('INACTIVE','ACTIVE','PAST_DUE','CANCELED')),
  provider text,
  provider_customer_id text,
  provider_subscription_id text,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.devices enable row level security;
alter table public.location_events enable row level security;
alter table public.subscriptions enable row level security;

create policy "owners can view their devices"
  on public.devices for select
  using (auth.uid() = owner_id);

create policy "owners can create their devices"
  on public.devices for insert
  with check (auth.uid() = owner_id);

create policy "owners can update their devices"
  on public.devices for update
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

create policy "owners can delete their devices"
  on public.devices for delete
  using (auth.uid() = owner_id);

create policy "owners can view their location events"
  on public.location_events for select
  using (auth.uid() = owner_id);

create policy "owners can create their location events"
  on public.location_events for insert
  with check (auth.uid() = owner_id);

create policy "owners can view their subscription"
  on public.subscriptions for select
  using (auth.uid() = owner_id);

create policy "owners can create their subscription"
  on public.subscriptions for insert
  with check (auth.uid() = owner_id);

create policy "owners can update their subscription"
  on public.subscriptions for update
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

create index if not exists devices_owner_id_idx on public.devices(owner_id);
create index if not exists location_events_device_id_recorded_at_idx
  on public.location_events(device_id, recorded_at desc);
create index if not exists location_events_owner_id_idx on public.location_events(owner_id);
